### ISSUE TITLE
crash during auth flow

### ISSUE THREAD

**Issue by wrboyce** [balena-io/sshproxy#67]
```
panic: interface conversion: interface {} is nil, not string
goroutine 3043014 [running]:
github.com/gliderlabs/ssh.(*sshContext).User(0xc0013e4880, 0x9afc00, 0xfcf990)
#011/go/src/github.com/gliderlabs/ssh/context.go:127 +0x9a
main.(*authHandler).publicKeyHandler(0xc00041e400, 0xbd7d20, 0xc0013e4880, 0x7f9ccc511380, 0xc001382910, 0x7f9ccc511380)
#011/go/src/github.com/balena-io/sshproxy/auth.go:84 +0x49
github.com/gliderlabs/ssh.(*Server).config.func2(0xbd3880, 0xc00009e200, 0xbce800, 0xc001382910, 0x217, 0x217, 0x0)
#011/go/src/github.com/gliderlabs/ssh/server.go:131 +0xca
golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc00009e200, 0xc0004b5110, 0x11, 0x40, 0x0)
#011/go/src/golang.org/x/crypto/ssh/server.go:523 +0x1bb2
golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc00009e200, 0xc0004b5110, 0xaaf128, 0x1b, 0x100e780)
```

**Comment by wrboyce** [comment]
Ref [`auth.go:84`](https://github.com/balena-io/sshproxy/blob/master/auth.go#L84)
